[postgres]
database_url = "host=localhost port=5432 user=root password=root dbname=taskmanager sslmode=disable"

[apiserver]
jwt_secret = "1337"
bind_addr = ":8080"
log_level = "debug"
caching_responses = true

[redis]
addr = "localhost:6379"
password = ""